options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/user-portal-399420/fastapi-ci-cd/fastapi-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/user-portal-399420/fastapi-ci-cd/fastapi-app:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'fastapi-app',
        '--image', 'us-east4-docker.pkg.dev/user-portal-399420/fastapi-ci-cd/fastapi-app:$SHORT_SHA',
        '--region', 'us-east4',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
images:
  - 'us-east4-docker.pkg.dev/user-portal-399420/fastapi-ci-cd/fastapi-app:$SHORT_SHA'
