name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker your-region-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE="your-region-docker.pkg.dev/$GCP_PROJECT/$ARTIFACT_REPO/fastapi-app:$GITHUB_SHA"
        docker build -t $IMAGE .
        docker push $IMAGE
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        ARTIFACT_REPO: ${{ secrets.ARTIFACT_REPO }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-app \
          --image=$IMAGE \
          --region=your-region \
          --platform=managed \
          --allow-unauthenticated
      env:
        IMAGE: "your-region-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.ARTIFACT_REPO }}/fastapi-app:${{ github.sha }}"
